### ISSUE TITLE
Global Emotes issue

### ISSUE THREAD

**Issue by Christian-Martinez1** [riolubruh/NitroPerks#6]
Hey mate,

When using global emotes I see the image in the message as I am typing, but when I send the message the emote gets replaced with the :tag: as if the emote is unlocked in the current server.

![image](https://user-images.githubusercontent.com/43798323/173636631-1e781607-8933-4565-ae93-aff97babd9c7.png)

**Comment by riolubruh** [comment]
oh yeah shit i noticed this like immediately when it was broken (i think cause of a change in Discord) but didn't commit it woops lol

**Comment by riolubruh** [comment]
fixed in 3.1.10
