### ISSUE TITLE
[Bug} All Stcikers Dismissed When Posted

### ISSUE THREAD

**Issue by Aezaeo** [riolubruh/NitroPerks#8]
When trying to post any sticker the ClydeBot dismiss message appears so the sticker posted isnt actually posted.

![Discord_JZxmFiJrYA](https://user-images.githubusercontent.com/24560181/175379829-a456d40b-1a38-4cb1-a028-0412d18eb52b.png)

**Comment by riolubruh** [comment]
I get this issue when SimpleDiscordCrypt is loaded, since it messes with stuff. I usually just disable SDC for this, which can be done by turning on/off Hardware Acceleration cause that restarts discord without SDC. If that isn't the case for you then I will look into it further

**Comment by Aezaeo** [comment]
@riolubruh I tried what you said, for some reason my Hardware Acceleration was on, but even after turning it off, I still get the same ClydeBot message popup.

**Comment by Aezaeo** [comment]
I managed to get stickers working with an unconventional workaround. I loaded "FreeStickersv1.2.1by An0" alongside NitroPerks. At first, testing stickers gave the same result, ClydeBot message. What fixed the issue was enabling NitroPerks "FreeStickers Compatibility Mode".

For peace of mind, I was testing NitroPerks loaded by itself initially. The reason I wanted to use your plugin is because it was a All-in-one solution. So I unloaded "FreeStickersv1.2.1by An0" & "Freemojiv1.7.3by Qb, An0" before testing NitroPerks.

 I also tested with "FreeStickersv1.2.1by An0" unloaded and NitroPerks "FreeStickers Compatibility Mode" enabled but all my stickers became greyed out. But with NitroPerks "FreeStickers Compatibility Mode" enabled and then loading "FreeStickersv1.2.1by An0" stickers began to work with NO ClydeBot message.
 
 I figured I'd share this with you in case you wanted to scour "FreeStickersv1.2.1by An0" to see what comparison you might draw to find a solution.

**Comment by riolubruh** [comment]
Ohhh lol
Yeah this plugin is _compatible_ with FreeStickers by An0, it doesn't _implement it_. Yeah what you 'found' is actually the intended usage of the plugin for if the user wants to use stickers.
I didn't really find it worth it to make a clone of FreeStickers to put it into my plugin, so I made the 'Compatibility Mode' workaround as a hotfix for people who actually use stickers.

**Comment by riolubruh** [comment]
Improved the README to guide people to the FreeStickers plugin.
